import streamlit as st

from backend.ui.renderers.helpers import (
    render_text,
    render_textarea,
    render_list,
    section_heading,
    divider
)

from backend.ui.renderers.epic_renderer import (
    render_epic
)


def render_project(project):

    # --------------------------------------------------
    # PROJECT DETAILS
    # --------------------------------------------------

    section_heading("Project Details")

    render_text(

        project,

        "project_name",

        "Project Name",

        "project_name"

    )

    render_textarea(

        project,

        "project_description",

        "Project Description",

        "project_description",

        height=150

    )

    divider()

    # --------------------------------------------------
    # EXECUTIVE SUMMARY
    # --------------------------------------------------

    section_heading(

        "Executive Summary"

    )

    summary = project.get(

        "executive_summary",

        {}

    )

    if not isinstance(summary, dict):

        summary = {}

        project["executive_summary"] = summary

    render_textarea(

        summary,

        "project_overview",

        "Project Overview",

        "project_overview",

        height=120

    )

    render_textarea(

        summary,

        "business_problem",

        "Business Problem",

        "business_problem",

        height=120

    )

    render_textarea(

        summary,

        "business_need",

        "Business Need",

        "business_need",

        height=120

    )

    render_textarea(

        summary,

        "proposed_solution",

        "Proposed Solution",

        "proposed_solution",

        height=120

    )

    render_list(

        summary,

        "business_benefits",

        "Business Benefits",

        "business_benefits"

    )

    render_textarea(

        summary,

        "expected_outcome",

        "Expected Outcome",

        "expected_outcome",

        height=120

    )

    divider()

    # --------------------------------------------------
    # DOCUMENT INFORMATION
    # --------------------------------------------------

    section_heading(

        "Document Information"

    )

    col1, col2 = st.columns(2)

    with col1:

        render_text(

            project,

            "document_version",

            "Document Version",

            "document_version"

        )

        render_text(

            project,

            "generated_by",

            "Generated By",

            "generated_by"

        )

    with col2:

        render_text(

            project,

            "generated_on",

            "Generated On",

            "generated_on"

        )

        render_text(

            project,

            "status",

            "Status",

            "status"

        )

    divider()

    # --------------------------------------------------
    # EPICS
    # --------------------------------------------------

    section_heading(

        "Project Backlog"

    )

    for index, epic in enumerate(

        project.get(

            "epics",

            []

        )

    ):

        render_epic(

            epic,

            index

        )