import streamlit as st

from backend.ui.renderers.helpers import (
    render_text,
    render_textarea,
    render_list,
    section_heading,
    divider,
)

from backend.ui.renderers.epic_renderer import (
    render_epic,
)


def render_project(project):

    # ======================================================
    # PROJECT INFORMATION
    # ======================================================

    st.markdown("## Project Information")

    st.markdown(
        """
        <div style="
            background:white;
            border:1px solid #E5E7EB;
            border-radius:18px;
            padding:24px;
            margin-bottom:24px;
            box-shadow:0 6px 20px rgba(0,0,0,.05);
        ">
            Configure and review the overall project information before reviewing
            the generated backlog.
        </div>
        """,
        unsafe_allow_html=True,
    )

    section_heading("Basic Information")

    render_text(
        project,
        "project_name",
        "Project Name",
        "project_name",
    )

    render_textarea(
        project,
        "project_description",
        "Project Description",
        "project_description",
        height=180,
    )

    divider()

    # ======================================================
    # EXECUTIVE SUMMARY
    # ======================================================

    section_heading("Executive Summary")

    summary = project.get("executive_summary", {})

    if not isinstance(summary, dict):
        summary = {}
        project["executive_summary"] = summary

    render_textarea(
        summary,
        "project_overview",
        "Project Overview",
        "project_overview",
        height=140,
    )

    render_textarea(
        summary,
        "business_problem",
        "Business Problem",
        "business_problem",
        height=140,
    )

    render_textarea(
        summary,
        "business_need",
        "Business Need",
        "business_need",
        height=140,
    )

    render_textarea(
        summary,
        "proposed_solution",
        "Proposed Solution",
        "proposed_solution",
        height=140,
    )

    render_list(
        summary,
        "business_benefits",
        "Business Benefits",
        "business_benefits",
    )

    render_textarea(
        summary,
        "expected_outcome",
        "Expected Outcome",
        "expected_outcome",
        height=140,
    )

    divider()

    # ======================================================
    # DOCUMENT DETAILS
    # ======================================================

    section_heading("Document Details")

    left, right = st.columns(2, gap="large")

    with left:

        render_text(
            project,
            "document_version",
            "Document Version",
            "document_version",
        )

        render_text(
            project,
            "generated_by",
            "Generated By",
            "generated_by",
        )

    with right:

        render_text(
            project,
            "generated_on",
            "Generated On",
            "generated_on",
        )

        render_text(
            project,
            "status",
            "Status",
            "status",
        )

    divider()

    # ======================================================
    # BACKLOG
    # ======================================================

    st.markdown("## Project Backlog")

    st.markdown(
        """
        <div style="
            background:white;
            border:1px solid #E5E7EB;
            border-radius:18px;
            padding:18px;
            margin-bottom:22px;
            box-shadow:0 6px 20px rgba(0,0,0,.05);
        ">
            Expand each Epic to review its Features, User Stories,
            Acceptance Criteria and Tasks before publishing.
        </div>
        """,
        unsafe_allow_html=True,
    )

    epics = project.get("epics", [])

    if not epics:

        st.info("No epics have been generated.")

        return

    for index, epic in enumerate(epics):

        render_epic(
            epic,
            index,
        )